### PR TITLE
Splitting out a few initial things

### PR DESCRIPTION
**Pull request by natew**
Ok so this will be where we track the general strategy for modularizing. Starting with npm install tools.

Why? We are moving to use webpack more behind the scenes. With views we could just watch *every* js file, but without them we need an entry point. This means we have to Webpack first, then run gulp afterwards.

I attempted to use [npm install webpack](https://github.com/ericclemmons/npm-install-webpack-plugin) but it's pretty limited compared to what we had. We install peer-deps, and can add hooks to filter out certain installs, send events on certain things, etc.

So, this is the *very early* start. All I've done is copy `npm.js` and it's dependency into it's own folder. And then copy out the `fns` file into it's own folder.

What needs doing:

- [x] package.json for npm needs migration
- [x] npm needs to take in options rather than use opts()
- [x] npm need to send events somehow on 'install:start', ':fail', ':success'
- [x] fs-extra tools package.json migration
- [x] fs-extra tools cleanup (remove a few functions that shouldn't be there)
- [x] build script needs updating to make bootstrap link them together
- [x] replace old npm/fns deps with new fns/npm packages
- [x] test and get working

We also will need to actually wrap the npm installer package with a webpack loader wrapper around it, but that can come after, so I guess:

- [x] make new package wrapped with webpack loader
- [ ] use and test it to install packages automatically during startup

### CODE REVIEW

**Comment by natew** [comment]
Pushed class based npm installer: needs hooks for when things happen so whoever uses it can get feedback on when things are successful/failed. Thoughts @steelbrain?

https://github.com/motion/motion/blob/94ec9bc6bbac84be7b0f91b58656a0c0f5cc7c3c/packages/npm/src/index.js

**Comment by steelbrain** [comment]
@natew Looks good, I did some tweaks to it, please take a look

**Comment by natew** [comment]
Looks perfect. Types and we'll split up. Is it working / tested? Next steps would be to make webpack loader to wrap it similar to the npm install one that exists. We also need a way to somehow pass callbacks to that loader so we can display in browser/cli the install progress properly.

**Comment by natew** [comment]
I know webpack allows adding custom parameters. Check the webpackConfig file to see the Babel ones. I'm mobile for now ping on slack!

**Comment by steelbrain** [comment]
@natew Can you please take a look at the CI failure? I'm very close to making package specific specs work https://circleci.com/gh/motion/motion/371

**Comment by steelbrain** [comment]
The CI build is now failing because of outdated node version, gonna update the CI config to run it on node v5.x

**Comment by steelbrain** [comment]
The CI builds are finally, passing again :tada: :tada: :tada: :tada:

**Comment by steelbrain** [comment]
I did some changes to the Makefile and bootstrap, the packages are now built using babel before they are linked, so npm no longer complains about bin files not existing. I've also rewritten the bootstrap js to bash to

**Comment by natew** [comment]
@steelbrain why go to bash? I'd think we'd want to move more towards js? Also does this lose some functionality? Either way, no big just wondering.

**Comment by steelbrain** [comment]
The reason I the bootstrap script in bash instead of JS is that JS has asynchrony in it's core, all the operations we want to do are sync and instead of using JS and then importing libraries like shelljs, I think it's more simpler to write it in plain bash

**Comment by natew** [comment]
Good enough for me, as long as it works well. The publish script let's leave JS it does quite a bit of logic and I'm super unfamiliar with bash. Not a fan of it in general if we can avoid.

**Comment by steelbrain** [comment]
@natew I've added specs for both the `fs` and `npm` package. They seem to be working well so far and helped me catch a few bugs while writing.

I've replaced `lib/npm.js` usage with `motion-npm`, Here's the things I could use some help on

- [ ] Integration with webpack
- [ ] New structure of spinner during installs

**Comment by steelbrain** [comment]
Currently our new loader works but due to webpack's aggressive caching, it doesn't really work without a webpack restart

**Comment by steelbrain** [comment]
Now if webpack is run with `--watch` it only fails the first time. But we still have to find a way to make it work even the first time

**Comment by steelbrain** [comment]
It has been fixed people! Wohoo! We no longer have to restart webpack or trigger a new compilation, the resolver now detects the changes successfully.

**Comment by steelbrain** [comment]
Gonna move transformers to webpack API in a separate PR

**Pull request merged**
