### PR TITLE
Full React compatability

### PR DESCRIPTION
**Pull request by natew**
This adds support for a much wider variety of apps. Basically, before:

- We only hot reloaded stuff not in your main bundle (global view files)

After:

- [x] We attempt to bundle everything using an entry point (defined by `config.entry`, default = `./main.js`)
  - [x] This bundle now is the only thing served by default (`internals.js`)
- [x] We attempt to recognize three types of React views: class, createClass, function
- [x] We hot reload files that export things that look "hot", (see above)
- [x] Support setting an entry point in config or cli
- [x] Support export default of a class from entry
- [x] Support new $() syntax for returning styles+dom (not static extracted)

Whats left to do:

- [x] Get tools building/loading using new system
- [x] Warn if no entry found with instructions
- [x] Make builds work with new system

Bring back static extraction eventually:
- [ ] Static extraction using $() in classes
- [ ] Static extraction using $() in createClass
- [ ] Static extraction using $() in functions
- [ ] Static extraction using $() when imported form somewhere else

Cleanups:

- [x] Rename internals.js => app.js or same name as appname

Lots of work in testing and making sure it all works:
- [ ] Test an app that uses redux connect + a variety of import structures
- [x] Test some bigger example app using react-router + redux + libraries
- [ ] Convert the reindex+motion gallery app and test that
- [ ] Test out site and see if it works, convert over to class syntax

A few things to decide and explore:
- [x] Implications with require().resolve (right now we just scan every js file, should we get a list from webpack instead?)
- [x] Remove view syntax altogether for now

### CODE REVIEW

**Comment by AriaFallah** [comment]
Looks really interesting! I'm looking forward to it.

**Comment by natew** [comment]
One thing we may be able to do is rely even more on webpack to answer the require.resolve() stuff. I think rather than putting a list of files into `internals.js` and pushing them onto exports.internals we can just use the Motion.file() to dynamically create that cache! Or at least we could compile that to happen on each file.

That we we're doing that lazily not up front.

**Comment by natew** [comment]
Ok broken things quite a bit, working on a slightly new strategy that should bring a lot more ease down the road. Also starting to question reality itself.

Basically, we were slurping up every file in your app before, but using require.resolve and also an entry point, that doesn't make much sense and forces you to never have "test" or "example" type folders. That's something the community won't want.

Since we're using webpack exclusively (after gulp) at the moment, I'm moving towards using webpack (and not gulp) to start. This means avoiding the entire gulp pipeline on startup.

One thing I think we can do is then just use Motion.file() to populate our cache of imports for hot reload use. I think.

Requires:

- [ ] Install babel-loader and start Webpack class
- [ ] Allow config to be shared between gulp/webpack babels
- [ ] Get meta info coming in through webpack loader
- [ ] Implement babel-runtime require scanning in webpack
- [ ] Make require statements insert another statement: Motion.registerImport()
- [ ] Motion.registerImport now collects our imports for hot reload use (lazily)
- [ ] Test hot reloads working with new import system
- [ ] Rejoice

**Comment by natew** [comment]
Getting this with latest:

```
ERROR in chunk react [entry]
react.prod.js
No template for dependency: TemplateArgumentDependency

ERROR in motion.prod.js from UglifyJs
Unexpected token: operator (>) [../nice-styles/lib/index.js:14,0]
```

**Comment by steelbrain** [comment]
Closed as most of this has been merged into master already

**Pull request closed without merging**
